spring:
  config:
    import: "optional:configserver:http://team1-configserver-service:8080/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://team1-eureka-server-svc:8080/eureka/  # Eureka Server 주소
