build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Noh Dong Jae"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371


cards:
  message: "test"
  contactDetails:
    name: "test"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
